language: objective-c
osx_image: xcode7.3
xcode_project: ./ios/TravisConfig.xcodeproj

before_install:
    - brew update
    - brew reinstall xctool
    - brew reinstall watchman
    - npm install
    
